# Generated by Django 3.2 on 2021-05-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Volunteer',
        ),
    ]
