# Generated by Django 3.2 on 2021-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_student_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='area',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
