# Generated by Django 3.2 on 2021-05-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteer_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_organisation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_volunteer',
        ),
    ]
