# Generated by Django 3.2 on 2021-05-25 18:51

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210525_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='SelectCountry',
            field=django_countries.fields.CountryField(default=True, max_length=2),
            preserve_default=False,
        ),
    ]
