# Generated by Django 3.2 on 2021-05-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteer_selectcountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='SelectCountry',
            new_name='select_country',
        ),
    ]
